# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: macos-latest

steps:
# - checkout: self
#     persistCredentials: true
#     clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install Dependecies'

- script: npm run limit
  displayName: 'Run lint'

- script: npm run test
  displayName: 'Run unit tests'

- script: |
    cd android
    bundle install
    fastlane build
  displayName: 'Build Android'

